# Generated by Django 4.0 on 2021-12-15 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlcoholCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'alcohol_categories',
            },
        ),
        migrations.CreateModel(
            name='DrinkingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'drinking_methods',
            },
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'flavors',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'genders',
            },
        ),
        migrations.CreateModel(
            name='Mbti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('information', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'mbtis',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('profile_image_url', models.URLField(max_length=500)),
                ('stack', models.IntegerField()),
                ('alcohol_limit', models.IntegerField()),
                ('alcohol_level', models.IntegerField()),
                ('comment', models.CharField(max_length=500)),
                ('favorite_place', models.CharField(max_length=200)),
                ('favorite_food', models.CharField(max_length=200)),
                ('hobby', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('kakao_login', models.CharField(max_length=100)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('class_number', models.PositiveSmallIntegerField()),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.gender')),
                ('mbti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mbti')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserFlavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.flavor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'user_flavors',
            },
        ),
        migrations.CreateModel(
            name='UserDrinkingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinking_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.drinkingmethod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'user_drinking_methods',
            },
        ),
        migrations.CreateModel(
            name='UserAlcoholCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcohol_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.alcoholcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'user_alcohol_categories',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time', models.DateTimeField()),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to='users.user')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respondent', to='users.user')),
            ],
            options={
                'db_table': 'meetings',
            },
        ),
        migrations.AddField(
            model_name='flavor',
            name='user',
            field=models.ManyToManyField(through='users.UserFlavor', to='users.User'),
        ),
        migrations.AddField(
            model_name='drinkingmethod',
            name='user',
            field=models.ManyToManyField(through='users.UserDrinkingMethod', to='users.User'),
        ),
        migrations.AddField(
            model_name='alcoholcategory',
            name='user',
            field=models.ManyToManyField(through='users.UserAlcoholCategory', to='users.User'),
        ),
    ]
