# Generated by Django 4.0 on 2021-12-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_meeting_is_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcoholcategory',
            name='surveys',
            field=models.ManyToManyField(related_name='alcohol_categories', through='users.SurveyAlcoholCategory', to='users.Survey'),
        ),
        migrations.AlterField(
            model_name='drinkingmethod',
            name='surveys',
            field=models.ManyToManyField(related_name='drinking_methods', through='users.SurveyDrinkingMethod', to='users.Survey'),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='surveys',
            field=models.ManyToManyField(related_name='flavors', through='users.SurveyFlavor', to='users.Survey'),
        ),
    ]
