# Generated by Django 4.0 on 2022-02-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_survey_alcohol_limit_alter_survey_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='alcohol_category_weight',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=5),
        ),
        migrations.AddField(
            model_name='survey',
            name='alcohol_level_weight',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=5),
        ),
        migrations.AddField(
            model_name='survey',
            name='alcohol_limit_weight',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=5),
        ),
        migrations.AddField(
            model_name='survey',
            name='drinking_method_weight',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=5),
        ),
        migrations.AddField(
            model_name='survey',
            name='flavor_weight',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=5),
        ),
    ]
